# Generated by Django 3.2.5 on 2021-07-06 05:15

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ip',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.IntegerField(default=0, validators=[book.models.numCheck]),
            preserve_default=False,
        ),
    ]
