# Generated by Django 2.1.1 on 2021-07-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('Africa', '아프리카'), ('Europe', '유럽'), ('Oceania', '오세아니아'), ('Asia', '아시아'), ('North America', '북아메리카'), ('South America', '남아메리카')], default='Asia', max_length=20),
        ),
    ]
